Update ai-cicd.yml

diff --git a/.github/workflows/ai-cicd.yml b/.github/workflows/ai-cicd.yml
--- a/.github/workflows/ai-cicd.yml
+++ b/.github/workflows/ai-cicd.yml
@@ -184,18 +184,16 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            echo "기존 uvicorn 종료"
-            # pkill -f uvicorn || echo "uvicorn not running, skipping"
+            echo "기존 uvicorn 종료 시도"
+            pkill -f uvicorn && echo "uvicorn 종료" || echo "uvicorn 없음"
             sleep 5
 
             echo "기존 소스코드 제거 및 새로운 코드 다운로드"
-            pwd
             cd /home/${USER:-ubuntu}
-            ls -al
             rm -rf 15-Leafresh-AI
 
             if [ -d 15-Leafresh-AI ]; then
-              echo "삭제 실패: 디렉토리가 여전히 존재합니다"
+              echo "삭제 실패: 디렉토리가 여전히 존재함"
               exit 1
             fi
 
@@ -221,17 +219,17 @@ jobs:
             echo "Google Credentials 생성"
             filename=$(grep "GOOGLE_APPLICATION_CREDENTIALS=" .env | sed 's/^[[:space:]]*//' | cut -d '=' -f2 | xargs)
             
-            if [ -z "$filename" ]; then
-              echo "❌ ERROR: GOOGLE_APPLICATION_CREDENTIALS 키가 .env에 없습니다"
-              cat .env
-              exit 1
-            fi
+            # if [ -z "$filename" ]; then
+            #   echo "ERROR: GOOGLE_APPLICATION_CREDENTIALS 키가 .env에 없습니다"
+            #   cat .env
+            #   exit 1
+            # fi
 
             echo "저장할 파일명: $filename"
             echo "${{ secrets.GCP_SA_KEY_DEV_BASE64 }}" | base64 -d > "$filename"
             
             # 유효한 JSON인지 확인
-            jq . "$filename" > /dev/null || { echo "❌ JSON 파일 확인 실패"; exit 1; }
+            jq . "$filename" > /dev/null || { echo "JSON 파일 확인 실패"; exit 1; }
 
 
             echo "uvicorn 실행"
